#!/bin/sh

cd /opt/ld
git clone https://github.com/kevincloud/instruqt-release-solve.git
cd instruqt-release-solve/challenge-01
echo "project_key = \"${LD_PROJECT_KEY}\"" >> terraform.tfvars
terraform init

exit 0
