#!/bin/bash

set -euo pipefail

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
    echo "Waiting for instruqt bootstrap to complete"
    sleep 1
done

apt-get -y update

apt-get -y install jq pip

ln -s /usr/bin/python3 /usr/bin/python

pip install launchdarkly-server-sdk flask flask_cors

echo "export LD_API_KEY=api-503dd436-920a-4380-9e66-8c2af6bb327e" > /root/apikey
source /root/apikey

# Cat with >> will append, not overwrite
cat >> /root/.bashrc <<-EOF
  source /root/apikey

EOF

# clone our code repo
cd /root
git clone https://github.com/kevincloud/launchdogly.git

# Create Code Server startup script
cat <<-EOF > /etc/systemd/system/launchdogly.service
[Unit]
Description=LaunchDogly App
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=root
WorkingDirectory=/root/launchdogly/track2
ExecStart=/usr/bin/python /root/launchdogly/track2/app.py
[Install]
WantedBy=multi-user.target
EOF

# Start Code Server
systemctl enable launchdogly
systemctl start launchdogly

# Create project
CLIENT_KEY=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/projects/launch-darkly-basics/environments/test' \
  -H 'Authorization: '${LD_API_KEY}'' | jq -r ._id)
echo "export CLIENT_KEY=${CLIENT_KEY}" >> /root/apikey

echo "var clientKey = \"${CLIENT_KEY}\";" > /root/launchdogly/track2/static/keys.js

# Create Enable Auto Rotate flag
ROTATE_FLAG_NAME=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/flags/launch-darkly-basics/enable-auto-rotate' \
  -H 'Authorization: '${LD_API_KEY}'' | jq -r .name)

if [ -z "$ROTATE_FLAG_NAME" ]; then
    curl -i -X POST \
    'https://app.launchdarkly.com/api/v2/flags/launch-darkly-basics' \
    -H 'Authorization: '${LD_API_KEY}'' \
    -H 'Content-Type: application/json' \
    -d '{
        "clientSideAvailability": {
            "usingEnvironmentId": true,
            "usingMobileKey": false
        },
        "key": "enable-auto-rotate",
        "name": "Enable Auto Rotate"
    }'
fi

# Create Background Color flag
COLOR_FLAG_NAME=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/flags/launch-darkly-basics/background-color' \
  -H 'Authorization: '${LD_API_KEY}'' | jq -r .name)

if [ -z "$COLOR_FLAG_NAME" ]; then
curl -i -X POST \
'https://app.launchdarkly.com/api/v2/flags/launch-darkly-basics' \
-H 'Authorization: '${LD_API_KEY}'' \
-H 'Content-Type: application/json' \
-d '{
    "clientSideAvailability": {
        "usingEnvironmentId": true,
        "usingMobileKey": false
    },
    "variations": [
        {
            "value": "#FFC0CB",
            "name": "Valentine'\''s Day"
        },
        {
            "value": "#90EE90",
            "name": "St. Patrick'\''s Day"
        },
        {
            "value": "#FFCBA4",
            "name": "Easter Day"
        },
        {
            "value": "#000000",
            "name": "No Holiday"
        }
    ],
    "key": "background-color-x",
    "name": "Background Color X"
}'
fi
