#!/bin/sh

# 
# Make sure the flag was created correctly
# 
FLAG_DATA=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/flags/'${LD_PROJECT_KEY}'/migrate-to-stripe-api' \
  -H 'Authorization: '${LAUNCHDARKLY_ACCESS_TOKEN}'')

FLAG_SDK=$(echo ${FLAG_DATA} | jq -r .clientSideAvailability.usingEnvironmentId)

if [ "$FLAG_SDK" != "true" ]; then 
    fail-message "The **SDKs using Client-side ID** box was not selected.\n\nGo to the flag's **Settings** tab to enable it."
    exit 1
fi

# 
# Make sure the code was added properly
# 
cd /opt/ld/talkin-ship-workshop-app/src/pages/api

LINE1=`grep -n '^.\s*const migrateToStripeApi.*$' checkout.ts | awk 'NR==1{print $1;}' | cut -b -2`
if [ "$LINE1" != "55" ]; then
    echo "You must replace lines 50-55 in '/src/pages/api/checkout.ts' with the code supplied."
    #exit 1
fi

exit 0
