#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

source /root/apikey

PROJECT_NAME=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/projects/launch-darkly-basics' \
  -H 'Authorization: '${LD_API_KEY}'' | jq -r .name)

if [ "$PROJECT_NAME" != "LaunchDarkly Basics" ]; then
    fail-message "The project key must be **launch-darkly-basics**"
    exit 1
fi

exit 0
