#!/bin/bash

source /root/apikey

PROJECT_NAME=$(curl -s -X GET \
  'https://app.launchdarkly.com/api/v2/projects/launch-darkly-basics' \
  -H 'Authorization: '${LD_API_KEY}'' | jq -r .name)

if [ "$PROJECT_NAME" != "LaunchDarkly Basics" ]; then
curl -i -X POST \
    https://app.launchdarkly.com/api/v2/projects \
    -H 'Authorization: '${LD_API_KEY}'' \
    -H 'Content-Type: application/json' \
    -d '{
        "key": "launch-darkly-basics",
        "name": "LaunchDarkly Basics"
    }'
fi

exit 0
